version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app-db
      - MYSQL_USER=app
      - MYSQL_PASSWORD=YES
# java -jar .\app-deadline.jar -P:jdbc.url=jdbc:mysql://localhost:3306/app-db -P:jdbc.user=app -P:jdbc.password=YES